name: Build

on: push

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - shell: bash
      env:
        MAILTRAPUSER: ${{ secrets.MAILTRAPUSER }}
      run: |
        sed -i -e 's/#MAILTRAPUSER#/'"$MAILTRAPUSER"'/g' Tests/SmtpTests/SmtpTests.swift
    - shell: bash
      env:
        MAILTRAPPASS: ${{ secrets.MAILTRAPPASS }}
      run: |
        sed -i -e 's/#MAILTRAPPASS#/'"$MAILTRAPPASS"'/g' Tests/SmtpTests/SmtpTests.swift
    - shell: bash
      env:
        GMAILUSER: ${{ secrets.GMAILUSER }}
      run: |
        sed -i -e 's/#GMAILUSER#/'"$GMAILUSER"'/g' Tests/SmtpTests/SmtpTests.swift
    - shell: bash
      env:
        GMAILPASS: ${{ secrets.GMAILPASS }}
      run: |
        sed -i -e 's/#GMAILPASS#/'"$GMAILPASS"'/g' Tests/SmtpTests/SmtpTests.swift
    - name: Build
      run: swift build --enable-test-discovery
    - name: Tests
      run: swift test --enable-test-discovery